### ISSUE TITLE
Use case scenarios

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-gatsby#221]
Danibelle asked me to create use case scenarios for DACs, campaigns, and milestones to demonstrate the validity of all three levels.

https://docs.google.com/document/d/1jpxVDSW4K1CieCJ4oqSeK4JrzEFeURHGFyjc_XzrlJE/edit?usp=sharing

**Comment by geleeroyale** [comment]
This could be used as an example in testing. Should be put into new category in `docs.giveth.io`

**Comment by WhyldWanderer** [comment]
Great! How can I help and who should I follow up with?

**Comment by geleeroyale** [comment]
I created a guide for testing - you can always expand on that @WhyldWanderer 

https://docs.giveth.io/docs/testing-guidelines
