### ISSUE TITLE
Donate QR code popup needs better styling

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-gatsby#372]
## 📋 Anything to add?
Current QR modal:
<img width="885" alt="Image 2021-01-14 at 4 48 37 pm" src="https://user-images.githubusercontent.com/5704285/104614830-e4da8800-5688-11eb-9eec-65673b4fe51d.png">

Redesigned QR modal:
<img width="677" alt="Image 2021-01-14 at 5 04 40 pm" src="https://user-images.githubusercontent.com/5704285/104616540-b067cb80-568a-11eb-80d3-75e03f886eca.png">

## ⏰ Urgency/Deadline/Blockers?
Before MVP launch.

## ❓ Why is it important?
Inconsistency with the rest of the site.

## 🤼‍ Reviewer
@markoprljic

**Comment by divine-comedian** [comment]
pending PR - https://github.com/Giveth/giveth-next/pull/169
